<?php declare(strict_types=1);


namespace EasyWsdl\ToPHP;


use EasyWsdl\ToPHP\Helpers\DirCreator;
use EasyWsdl\ToPHP\Helpers\NormalizeHelper;
use Nette\PhpGenerator\Helpers;
use Nette\PhpGenerator\Method;
use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\PhpNamespace;
use Nette\PhpGenerator\Printer as NettePrinter;


class Printer extends NettePrinter
{

    /**
     * @param string  $filePath
     * @param string  $className
     * @param PhpFile $phpFile
     */
    public static function generateToFile(string $filePath, string $className, PhpFile $phpFile): void
    {
        DirCreator::createDir($filePath, 0666, true);
        $file = fopen($filePath . NormalizeHelper::DIRECTORY_SEPARATOR . $className . '.php', 'w');
        fwrite($file, (new self)->printFile($phpFile));
    }

    /**
     * @param Method            $method
     * @param PhpNamespace|null $namespace
     * @return string
     */
    public function printMethod(Method $method, PhpNamespace $namespace = null): string
    {
        $method->validate();

        return Helpers::formatDocComment($method->getComment() . "\n")
            . ($method->isAbstract() ? 'abstract ' : '')
            . ($method->isFinal() ? 'final ' : '')
            . ($method->getVisibility() ? $method->getVisibility() . ' ' : '')
            . ($method->isStatic() ? 'static ' : '')
            . 'function '
            . ($method->getReturnReference() ? '&' : '')
            . $method->getName()
            . ($params = $this->printParameters($method, $namespace))
            . $this->printReturnType($method, $namespace)
            . ($method->isAbstract() || $method->getBody() === null
                ? ";\n"
                : (strpos($params, "\n") === false ? "\n" : ' ')
                . "{\n"
                . rtrim($method->getBody()) . "\n")
            . "}\n";
    }

    public static function setFile(): PhpFile
    {
        $file = new PhpFile;
        $file->setStrictTypes();
        $file->setComment('This file has autogenerated stub. Please remember if you edit this file.');

        return $file;
    }

}